name: Publish the Python SDK to PyPi

on:
    workflow_dispatch:

jobs:
    build-and-publish:
        name: Build and Publish
        runs-on: ubuntu-latest
        steps:
            - name: Build and publish to pypi
              uses: JRubics/poetry-publish@v2.0
              with:
                  pypi_token: ${{ secrets.PYTHON_SDK_PYPI_TOKEN }}
